- hosts: node
  gather_facts: yes
  become: yes
  vars_prompt:
    - name: "nodeTypeT"
      prompt: "************************\n[0]:validator\n[1]:boot\n[2]:writer\nPlease, choose which type of node are you updating"
      private: no
    - name: "networkT"
      prompt: "************************\n[0]:mainnet-omega\n[1]:open-protestnet\n[2]:legacy-protestnet (DEPRECATED)\nPlease, choose in which network are you updating"
      private: no

  vars:
    update: true
  roles:
    - role: lacchain-writer-node
      when: (nodeTypeT == '2')
    - role: lacchain-validator-node
      when: (nodeTypeT == '0')
    - role: lacchain-bootnode
      when: (nodeTypeT == '1')  
    - role: lacchain-tessera-node
      when: (nodeTypeT == '3')  
        