- hosts: node
  gather_facts: yes
  become: yes
  vars:
    install: true
  vars_prompt:
    - name: "Please read the terms and conditions before installing this software: https://github.com/lacchain/pantheon-network/blob/master/TERMS_AND_COND_WRITER_NODE.md .Press ENTER  "

    - name: "haveRead"
      prompt: "Have you read the Terms and Conditions of use of LACChain Test Network? [Y/N]"
      private: no

    - name: "isAgree"
      prompt: "Do you agree with the Terms and Conditions of use of LACChain Test Network? [Y/N]"
      private: no
      
  tasks:
    - fail:
        msg: 'Please Accept the conditions by typing Y when prompted.'
      when: " (haveRead != 'Y' and haveRead != 'y') or ( isAgree != 'Y' and isAgree != 'y' ) "

    - debug:
        msg: "Starting Installation"

- hosts: tessera
  gather_facts: yes
  become: yes
  vars:
    install: true

  roles:
    - role: lacchain-tessera-node
      when: tessera | bool

- hosts: node
  gather_facts: yes
  become: yes
  vars_prompt:
    - name: "nodeTypeT"
      prompt: "************************\n[0]:validator\n[1]:boot\n[2]:writer\n[3]:tessera\nPlease, choose which type of node are you deploying"
      private: no
    - name: "networkT"
      prompt: "************************\n[0]:mainnet-omega\n[1]:pro-testnet\n[2]:testnet-david19\nPlease, choose in which network are you deploying"
      private: no

  vars:
    install: true
  roles:
    - role: lacchain-validator-node
      when: (nodeTypeT == '0')
    - role: lacchain-bootnode
      when: (nodeTypeT == '1')  
    - role: lacchain-writer-node
      when: (nodeTypeT == '2')
    - role: lacchain-tessera-node
      when: (nodeTypeT == '3')  
        