{{- if eq .Values.cluster.provider "azure" }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "besu-node.fullname" . }}-storage
  namespace: {{ .Release.Namespace }}
provisioner: kubernetes.io/azure-file
reclaimPolicy: {{ .Values.cluster.reclaimPolicy }}
allowVolumeExpansion: true
mountOptions:
{{- if ( eq .Values.cluster.type "aro" ) }} 
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - cache=strict
  - actimeo=30
  - noperm
{{- else }} 
  - dir_mode=0755
  - file_mode=0755
  - uid=1000
  - gid=1000
{{- end }} 
  - mfsymlinks
parameters:
  skuName: Standard_LRS
{{- if ( eq .Values.cluster.type "aro" ) }} 
  location: {{ .Values.azure.storageClass.location }}
  storageAccount: {{ .Values.azure.storageClass.storageAccount }}
  resourceGroup: {{ .Values.azure.storageClass.resourceGroup }}
  secretNamespace: kube-system
reclaimPolicy: Delete
volumeBindingMode: Immediate
{{- end }} 
{{- else if eq .Values.cluster.provider "aws" }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "besu-node.fullname" . }}-storage
  namespace: {{ .Release.Namespace }}
provisioner: ebs.csi.aws.com
reclaimPolicy: {{ .Values.cluster.reclaimPolicy }}
allowVolumeExpansion: true
parameters:
  type: gp3
  fsType: ext4

{{- else if eq .Values.cluster.provider "google" }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "besu-node.fullname" . }}-storage
  namespace: {{ .Release.Namespace }}
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
reclaimPolicy: {{ .Values.cluster.reclaimPolicy }}
allowVolumeExpansion: true

{{- else }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "besu-node.fullname" . }}-storage
  namespace: {{ .Release.Namespace }}
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: {{ .Values.cluster.reclaimPolicy }}
  storageClassName: {{ include "besu-node.fullname" . }}-storage
  capacity:
    storage: "{{ .Values.storage.sizeLimit }}"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/{{ include "besu-node.fullname" . }}"

{{- end }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "besu-node.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName:  {{ include "besu-node.fullname" . }}-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
{{- if eq .Values.deploy.network "open-protest-net" }}
      storage: {{ .Values.volumen.resources.storage.openprotest }}
{{- else if eq .Values.deploy.network "protest-net" }}
      storage: {{ .Values.volumen.resources.storage.protest }}
{{- else if eq .Values.deploy.network "main-net" }}
      storage: {{ .Values.volumen.resources.storage.mainnet }}
{{- else }}
      storage: {{ .Values.volumen.resources.storage.mainnet }}
{{- end }} 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  {{ include "besu-node.fullname" . }}-ethstats-pvc 
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName:  {{ include "besu-node.fullname" . }}-storage
  accessModes:
{{- if ( eq .Values.cluster.type "aro" ) }} 
    - ReadWriteMany
{{- else }} 
    - ReadWriteOnce
{{- end }}
  resources:
    requests:
      storage: 1Gi
