{{- if eq .Values.cluster.provider "azure" }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "besu-node.fullname" . }}-storage
  namespace: {{ .Release.Namespace }}
provisioner: csi.trident.netapp.io
reclaimPolicy: {{ .Values.cluster.reclaimPolicy }}
allowVolumeExpansion: true
mountOptions:
  - nconnect=16
parameters:
  backendType: "azure-netapp-files"
  fsType: "nfs"
  selector: "performance=Standard"
{{- else if eq .Values.cluster.provider "aws" }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "besu-node.fullname" . }}-storage
  namespace: {{ .Release.Namespace }}
provisioner: ebs.csi.aws.com
reclaimPolicy: {{ .Values.cluster.reclaimPolicy }}
allowVolumeExpansion: true
parameters:
  type: gp3
  fsType: ext4

{{- else if eq .Values.cluster.provider "google" }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "besu-node.fullname" . }}-storage
  namespace: {{ .Release.Namespace }}
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
reclaimPolicy: {{ .Values.cluster.reclaimPolicy }}
allowVolumeExpansion: true

{{- else }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "besu-node.fullname" . }}-storage
  namespace: {{ .Release.Namespace }}
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: {{ .Values.cluster.reclaimPolicy }}
  storageClassName: {{ include "besu-node.fullname" . }}-storage
  capacity:
    storage: "{{ .Values.storage.sizeLimit }}"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/{{ include "besu-node.fullname" . }}"

{{- end }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "besu-node.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName:  {{ include "besu-node.fullname" . }}-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
{{- if eq .Values.deploy.network "open-protest-net" }}
      storage: {{ .Values.volumen.resources.storage.openprotest }}
{{- else if eq .Values.deploy.network "protest-net" }}
      storage: {{ .Values.volumen.resources.storage.protest }}
{{- else if eq .Values.deploy.network "main-net" }}
      storage: {{ .Values.volumen.resources.storage.mainnet }}
{{- else }}
      storage: {{ .Values.volumen.resources.storage.mainnet }}
{{- end }} 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  {{ include "besu-node.fullname" . }}-ethstats-pvc 
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName:  {{ include "besu-node.fullname" . }}-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
