---
 - name: cd repos
   shell: cd /etc/yum.repos.d/

 - name: replace centos repos
   shell: sed -i -e "s|mirrorlist=|#mirrorlist=|g" /etc/yum.repos.d/CentOS-*
    
 - name: replace centos repos mirror
   shell: sed -i -e "s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-*
 
 - name: Clean cache
   shell: dnf clean all
 

 - name: update repo centos
   shell: dnf -y  swap centos-linux-repos centos-stream-repos



 - name: install dependencies for {{ ansible_distribution }}
   yum:
    name:
      - "gmp-devel"
      - "gcc"
      - "gcc-c++"
      - "make"
      - "openssl-devel"
      - "ncurses-devel"
      - "wget"
      - "nmap-ncat"
      - "epel-release"
      - "git"

 - name: install leveldb for {{ ansible_distribution }}
   yum:
    name:
      - "libsodium-devel"
      - "libdb-devel"
      - "leveldb-devel"
