---
- name: Checking if Relay Signer exists
  stat:
    path: "/root/lacchain/gas-relay-signer/config.toml"
  register: relay_signer

- name: Download Relay Signer code
  git:
        repo: "https://github.com/LACNetNetworks/gas-management.git"
        dest: "/root/lacchain/gas-relay-signer"
        version: v1.0.1
  when: (networkT == '1' and not relay_signer.stat.exists) 

- name: Download Relay Signer code
  git:
        repo: "https://github.com/LACNetNetworks/gas-management.git"
        dest: "/root/lacchain/gas-relay-signer"
        version: v1.0.0
  when: (networkT == '0' and not relay_signer.stat.exists) 


- name: semanage gas-relay-signer service on centos8
  shell: semanage fcontext -a -t bin_t '/root/lacchain/gas-relay-signer/gas-relay-signer'
  when: ((ansible_distribution |lower == 'centos' or ansible_distribution |lower == 'oraclelinux') and ansible_distribution_major_version == "8") 

- name: restorecon gas-relay-signer service on centos8
  shell: restorecon -Fv /root/lacchain/gas-relay-signer/gas-relay-signer
  when: ((ansible_distribution |lower == 'centos' or ansible_distribution |lower == 'oraclelinux') and ansible_distribution_major_version == "8") 


- name: Generate Relay Signer configuration file
  template:
    src: "relay-signer-config.j2"
    dest: "~/lacchain/gas-relay-signer/config.toml"
    mode: 0644
  when: not relay_signer.stat.exists 

- name: Get Key
  shell: cat ~/lacchain/data/key
  register: key
  when: not relay_signer.stat.exists 

- name: Set WRITER_KEY default
  template:
    src: writer-key.sh.j2
    dest: /etc/profile.d/writer-key.sh
    mode: 0644
  when: not relay_signer.stat.exists 

- name: reset environment 
  shell: bash -c 'source /etc/profile.d/writer-key.sh'
  when: not relay_signer.stat.exists 

- name: Copy service file to systemd
  copy:
    src: "{{ role_path }}/files/relaysigner.service"
    dest: /lib/systemd/system/relaysigner.service
    mode: 0775
  when: not relay_signer.stat.exists 
  
- name: Enable service relaysigner
  service:
    name: relaysigner
    enabled: yes