- name: install dependencies for nginx from openresty
  yum:
    name:
      - wget
      - gnupg 
      - ca-certificates

- name: import repo openresty centos {{ansible_distribution_major_version }}
  shell: wget 'https://openresty.org/package/centos/openresty.repo'
  become: true
  when: ((ansible_distribution |lower == 'centos' or ansible_distribution |lower == 'redhat' or ansible_distribution |lower == 'oraclelinux') and ansible_distribution_major_version == "8")  

- name: import repo openresty centos {{ansible_distribution_major_version }}
  shell: wget 'https://openresty.org/package/centos/openresty2.repo'
  become: true
  when: ((ansible_distribution |lower == 'centos' or ansible_distribution |lower == 'redhat'  or ansible_distribution |lower == 'oraclelinux') and ansible_distribution_major_version == "9")  

- name: yum repositories. centos {{ansible_distribution_major_version }}
  shell: sudo mv openresty.repo /etc/yum.repos.d/
  when: ((ansible_distribution |lower == 'centos' or ansible_distribution |lower == 'redhat' or ansible_distribution |lower == 'oraclelinux') and ansible_distribution_major_version == "8")  

- name: yum repositories. centos {{ansible_distribution_major_version }}
  shell: sudo mv openresty2.repo /etc/yum.repos.d/openresty.repo
  when: ((ansible_distribution |lower == 'centos' or ansible_distribution |lower == 'redhat'  or ansible_distribution |lower == 'oraclelinux') and ansible_distribution_major_version == "9")

- name: install   openresty
  shell: dnf -y install openresty



- name: install  openresty-resty
  shell: dnf -y install openresty-resty

- name: install   openresty-opm
  shell: dnf -y install openresty-opm

- name: set   locale LC_CTYPE en_US.UTF-8
  shell: export LC_CTYPE=en_US.UTF-8

- name: set  locale LC_ALL en_US.UTF-8
  shell: export LC_ALL=en_US.UTF-8

- name: installing the lua-resty-http
  shell: opm get pintsized/lua-resty-http

- name: loading it with the resty utility
  shell: resty -e 'require "resty.http"'

- name: open port tcp 60606
  shell: firewall-cmd --zone=public --permanent --add-port 60606/tcp
  when: ((ansible_distribution |lower == 'centos' or ansible_distribution |lower == 'redhat' ) and ansible_distribution_major_version == "9")  

- name: open port upd 60606
  shell: firewall-cmd --zone=public --permanent --add-port 60606/udp
  when: ((ansible_distribution |lower == 'centos' or ansible_distribution |lower == 'redhat' ) and ansible_distribution_major_version == "9") 

- name: reload firewall
  shell: firewall-cmd --reload
  when: ((ansible_distribution |lower == 'centos' or ansible_distribution |lower == 'redhat' ) and ansible_distribution_major_version == "9") 
