---
# tasks file for docker-ce-ansible-role

- name: Install prerequisite packages
  shell: dnf install -y dnf-utils zip unzip
  become: yes  


- name: Enable additional repository (for oracle only)
  shell: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  become: yes 

- name: Install additional prerequisite packages (for oracle only)
  shell: dnf remove -y runc
  become: yes  


- name: Install Docker CE
  shell: dnf install -y docker-ce --nobest
  become: yes

- name: Enable docker
  shell: systemctl enable docker.service
  become: yes

- name: Start docker
  shell: systemctl start docker.service
  become: yes    
