- name: install java 17 for {{ ansible_distribution }}
  shell: | 
    wget https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.rpm
    sudo yum -y install ./jdk-17_linux-x64_bin.rpm
    java -version