---
- name: set mainnet as network chosen
  set_fact:
    network: "mainnet"
  when: (networkT == '0')

- name: set protestet as network chosen
  set_fact:
    network: "protestnet"
  when: (networkT == '1')  

- name: Deploying node
  debug:
    msg: You are deploying a WRITER on {{network}}

- name: get public ip
  shell: dig +short myip.opendns.com @resolver1.opendns.com 2>/dev/null || curl -s --retry 2 icanhazip.com
  register: ip_address
  when: node_ip is not defined

- name: setting ip to use
  set_fact:
    node_ip: "{{ip_address.stdout}}"
  when: node_ip is not defined

- name: setting besu version
  set_fact:
    besu_release_version: "21.1.6"
  when: (networkT == '1')

- name: setting orion ip
  set_fact:
    node_ip_orion: "{%for host in groups['orion']%}{{hostvars[host]['node_ip']}}{% endfor %}" 
  when: orion | bool

- name: Install Writer Node
  import_tasks: "install.yaml"
  when: install | default(False) | bool

- name: Update Writer Node
  import_tasks: "update.yaml"
  when: update | default(False) | bool