---
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes

- name: install dependencies for {{ ansible_distribution }}
  apt:
    name:
      - software-properties-common
      - unzip
      - wget
      - git
      - make
      - gcc
      - build-essential
      - libdb-dev
      - zlib1g-dev
      - libtinfo-dev
      - sysvbanner
      - psmisc
      - libdb5.3-dev
      - cron  