apiVersion: v1
kind: ConfigMap
metadata:
  name: besu-config-toml-configmap-writer
  labels:
    app: besu-config-toml-configmap-writer
  namespace: lacchain-main-net
data:
  config.toml.template: |-
    # Node Information
    data-path="/data"
    genesis-file="/etc/genesis/genesis.json"

    # TODO : insert as command line & mount Volume
    # rpc-http-authentication-credentials-file="none"
    # TODO : insert as command line & mount Volume
    # rpc-ws-authentication-credentials-file="none"
    logging="INFO"

    min-gas-price=0
    # Transaction Pool
    #tx-pool-retention-hours=6
    #tx-pool-max-size=1024

    # P2P network
    p2p-enabled=true
    discovery-enabled=true
    p2p-host="${P2P_HOST}"
    p2p-port=${P2P_PORT}
    bootnodes=["enode://ed664ba8ec6959b1b2bd70dce16286cb1688f2f8ab13b8571b0ba4eeb73df9d5f5acb32efff7aabd71fc865d374d2e9c96c524ca543c9aa65dd6543f83852521@35.229.62.151:60606","enode://b10272c5206cd1ec12c6737a41df471e6384cde3e6522a212e3839be09981133eccdacc4ef1c7aacd3aeb63debfa82643d92820bb9f045245cb6badb74dff198@34.138.6.187:60606"]


    #host-allowlist=["*"]
    host-whitelist=["*"]

    # JSON-RPC
    rpc-http-enabled=true
    rpc-http-host="0.0.0.0"
    rpc-http-port=4545
    rpc-http-api=["ETH","NET","IBFT","WEB3","EEA","PRIV"]
    rpc-http-cors-origins=["*"]
    rpc-http-authentication-enabled=false

    # GRAPHQL-RPC
    graphql-http-enabled=true
    graphql-http-host="0.0.0.0"
    graphql-http-port=4547
    graphql-http-cors-origins=["*"]

    # WebSockets API
    rpc-ws-enabled=true
    rpc-ws-host="0.0.0.0"
    rpc-ws-port=4546
    rpc-ws-api=["ETH","NET","IBFT","WEB3","EEA","PRIV"]
    rpc-ws-authentication-enabled=false

    # Metrics
    metrics-push-enabled=true
    metrics-push-port=9091
    metrics-push-host="35.231.59.254"
    metrics-push-interval=5
    metrics-push-prometheus-job="${NODE_NAME}"

  

