apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data-writer-tessera
  namespace: lacchain-david19
spec:
  storageClassName: sc-writer-tessera-david19
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
