apiVersion: v1
kind: Service
metadata:
  name: validator-besu-lacchain
  labels:
    app: lacchain-validatornode
  namespace: lacchain-david19
spec:
  type: LoadBalancer
  selector:
    app: lacchain-validatornode
  ports:
    - port: 60606
      targetPort: 60606
      protocol: TCP
      name: rlpx
    - port: 4545
      targetPort: 4545
      protocol: TCP
      name: json-rpc
    - port: 4546
      targetPort: 4546
      protocol: TCP
      name: ws
    - port: 4547
      targetPort: 4547
      protocol: TCP
      name: graphql
  loadBalancerIP: 34.70.167.44
