---
# file: oracle-java/tasks/installation/debian/main.yml
#
# Task file to install Oracle Java Development Kit in a system with a Debian based Linux distribution.
#

#become: yes
- name: debian | ensure the apt repository is present
  apt_repository: repo="{{ oracle_java_apt_repository }}"
    update_cache=yes
    state=present

#become: yes
- name: debian | ensure Java is installed
  apt: name="{{ oracle_java_deb_package }}"
    state={{ oracle_java_state }}
    cache_valid_time={{ oracle_java_cache_valid_time }}
    update_cache=yes
  register: oracle_java_task_apt_install
#become: yes