---

- name: Print some info information 
  vars: 
    msg: |
        Ansible Distribution: {{ ansible_distribution }}
        Ansible Dist version: {{ ansible_distribution_version }}
        Ansible Dist version: {{ ansible_distribution_major_version }}
        
  debug: 
    msg: "{{ msg.split('\n') }}"


- name: install dependencies for  {{ ansible_distribution }}
  import_tasks: "ubuntu-dependencies.yml"
  when: ansible_distribution |lower == 'ubuntu'

- name: install dependencies for  {{ ansible_distribution }}
  import_tasks: "rhel-dependencies.yml"
  when: ((ansible_distribution |lower == 'redhat') or (ansible_distribution |lower == 'centos' and ansible_distribution_major_version < "8"))



- name: install dependencies for  {{ ansible_distribution }}
  import_tasks: "centos8-dependencies.yml"
  when: ((ansible_distribution |lower == 'centos' or ansible_distribution  |lower == 'oraclelinux' or ansible_distribution  |lower == 'rocky') and ansible_distribution_major_version >= "8")

- name: install java for {{ ansible_distribution }}
  import_tasks: "install-java-ubuntu.yaml"
  when: ansible_distribution |lower == 'ubuntu'

- name: install java for {{ ansible_distribution }}
  import_tasks: "install-java-centos.yaml"
  when: (ansible_distribution |lower == 'redhat') or (ansible_distribution |lower == 'centos' and ansible_distribution_major_version < "8")  

- name: install java for {{ ansible_distribution }}
  import_tasks: "install-java-centos8.yaml"
  when: ((ansible_distribution |lower == 'centos' or ansible_distribution |lower == 'oraclelinux' or ansible_distribution  |lower == 'rocky') and ansible_distribution_major_version >= "8")  
  
- name: install docker for {{ ansible_distribution }}
  import_tasks: "install-docker-ubuntu.yaml"
  when: ansible_distribution |lower == 'ubuntu'

- name: install docker for {{ ansible_distribution }}
  import_tasks: "install-docker-redhat.yaml"
  when: (ansible_distribution |lower == 'redhat') or (ansible_distribution |lower == 'centos' )  or (ansible_distribution |lower == 'rocky' ) 

- name: install besu
  import_tasks: "install-besu.yaml"

- name: init besu
  import_tasks: "init-besu.yaml"

- name: start node
  import_tasks: "start-node.yaml"
  when: first_node

- name: install Rotation Validator
  import_tasks: "install-rotation-validator.yaml"
  
- name: init Rotation Validator
  import_tasks: "init-rotation-validator.yaml"

- name: start ethstats client
  import_tasks: "start-ethstats-client.yaml"

- name: start Rotation Validator
  import_tasks: "start-rotation-validator.yaml"

- name: clean files
  import_tasks: "clean-files.yaml"