version: "3.6"
services:
  registry: 
    image: lacnetnetworks/lacchain-besu:21.1.6
    container_name: bootnode-besu-lacchain
    environment:
      BESU_LOGGING: INFO
      BESU_P2P_HOST: 179.6.80.43
      BESU_P2P_PORT: 60606
      BESU_RPC_HTTP_PORT    : 4545
      BESU_RPC_WS_PORT      : 4546
      BESU_GRAPHQL_HTTP_PORT: 4547
    entrypoint:
      - /bin/sh
      - -c
    command:
      - |
        /opt/besu/bin/besu --genesis-file=/etc/genesis/genesis.json --data-path=/data/besu public-key  export-address --to=/data/besu/nodeAddress
        sleep 3; 
        /opt/besu/bin/besu  --config-file=/etc/besu/config.toml  --node-private-key-file=/data/besu/key  
    ports:
      - 4545:4545
      - 4547:4547
      - 4546:4546
      - 60606:60606
    volumes:
      - ./validator1/data:/data/besu
      - ./files/genesis.json:/etc/genesis/genesis.json
      - ./files/config-validator.toml:/etc/besu/config.toml