apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data-bootnode
  namespace: lacchain-david19
spec:
  storageClassName: sc-bootnode-david19
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi